/* This file is part of OpenMalaria.
 * 
 * Copyright (C) 2005-2014 Swiss Tropical and Public Health Institute
 * Copyright (C) 2005-2014 Liverpool School Of Tropical Medicine
 * 
 * OpenMalaria is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#ifndef Hmod_LSTMDrugOnComp
#define Hmod_LSTMDrugOnComp

#include "Global.h"
#include "LSTMDrug.h"
#include "LSTMDrugType.h"

using namespace std;

namespace OM {

namespace PkPd {
struct DoseParams;
}
namespace util {
namespace checkpoint {
void operator& (multimap<double,PkPd::DoseParams> x, ostream& stream);
void operator& (multimap<double,PkPd::DoseParams>& x, istream& stream);
}
}

namespace PkPd {

/** A class holding pkpd drug use info.
 * 
 * One compartment model
 *
 * Each human has an instance for each type of drug present in their blood. */
class LSTMDrugOneComp : public LSTMDrug {
public:
    /** Create a new instance. */
    LSTMDrugOneComp (const LSTMDrugType&);
    
    inline size_t getIndex() const {
        return typeData.getIndex();
    }
    
    /** Indicate a new medication this time step.
     *
     * Converts qty in mg to concentration, and stores along with time (delay past
     * the start of the current time step) in the doses container.
     * 
     * @param time Time of administration, in days (should be at least 0 and
     *  less than 1).
     * @param qty Amount of active ingredient, in mg
     * @param bodyMass Body mass of patient, in kg
     */
    void medicate (double time, double qty, double bodyMass);
    
    /** Returns the total drug factor for one drug over one day.
     *
     * The drug factor values generated by this function must be multiplied to
     * reflect the drug action of all drugs in one day.
     *
     * This doesn't adjust concentration because this function may be called
     * several times (for each infection) per time step, or not at all. */
    double calculateDrugFactor(uint32_t genotype);

    /** Updates concentration variable and clears day's doses.
     *
     * @returns true if concentration is negligible (this class instance can be removed). */
    bool updateConcentration ();
    
    /** Get the concentration. */
    inline double getConcentration()const{ return concentration; }

protected:
    virtual void checkpoint (istream& stream);
    virtual void checkpoint (ostream& stream);
    
    /// Always links a drug instance to its drug-type data
    const LSTMDrugType& typeData;
    
    /// Concentration in blood; units: mg / l.
    double concentration;
};

}
}
#endif
