FROM ubuntu:jammy AS builder
WORKDIR /

ARG OM_BRANCH=main

# schema-48.0 release does not have changes required to build OM on linux/arm64.
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential ca-certificates git libz-dev python3 cmake libgsl-dev libxerces-c-dev xsdcxx libboost-dev \
  && rm -rf /var/lib/apt/lists/* \
  && git clone --depth 1 --branch ${OM_BRANCH} https://github.com/SwissTPH/openmalaria.git \
  && cd openmalaria \
  && mkdir build \
  && cd build \
  && cmake -DCMAKE_BUILD_TYPE=Release .. \
  && make -j8 \
  && cd .. \
  && mkdir openmalariaRelease \
  && cp build/openMalaria openmalariaRelease/ \
  && cp build/schema/scenario_current.xsd openmalariaRelease/scenario_48.xsd \
  && cp build/schema/scenario_current.xsd openmalariaRelease/ \
  && cp test/*.csv openmalariaRelease/

FROM ubuntu:jammy AS openmalaria
WORKDIR /om/
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential libgsl27 libxerces-c3.2 \
  && rm -rf /var/lib/apt/lists/*
COPY --from=builder /openmalaria/openmalariaRelease/* ./
ENTRYPOINT ["/om/openMalaria"]